SUBROUTINE CLEAN_DATA(YDTRC)
  USE YOMTRC, ONLY: TTRC
  TYPE(TTRC), INTENT(INOUT) :: YDTRC

  IF(ALLOCATED(YDTRC%GRSURF  ))DEALLOCATE(YDTRC%GRSURF)
  IF(ALLOCATED(YDTRC%GDEOTI  ))DEALLOCATE(YDTRC%GDEOTI)
  IF(ALLOCATED(YDTRC%GDEOTI2 ))DEALLOCATE(YDTRC%GDEOTI2)
  IF(ALLOCATED(YDTRC%GUEOTI  ))DEALLOCATE(YDTRC%GUEOTI)
  IF(ALLOCATED(YDTRC%GUEOTI2 ))DEALLOCATE(YDTRC%GUEOTI2)
  IF(ALLOCATED(YDTRC%GEOLT   ))DEALLOCATE(YDTRC%GEOLT)
  IF(ALLOCATED(YDTRC%GEOXT   ))DEALLOCATE(YDTRC%GEOXT)
  IF(ALLOCATED(YDTRC%GRPROX  ))DEALLOCATE(YDTRC%GRPROX)
  IF(ALLOCATED(YDTRC%GMIXP   ))DEALLOCATE(YDTRC%GMIXP)
  IF(ALLOCATED(YDTRC%GFLUXC  ))DEALLOCATE(YDTRC%GFLUXC)
  IF(ALLOCATED(YDTRC%GDEOSI  ))DEALLOCATE(YDTRC%GDEOSI)
  IF(ALLOCATED(YDTRC%GUEOSI  ))DEALLOCATE(YDTRC%GUEOSI)
  IF(ALLOCATED(YDTRC%GMU0    ))DEALLOCATE(YDTRC%GMU0)
  IF(ALLOCATED(YDTRC%GMU0_MIN))DEALLOCATE(YDTRC%GMU0_MIN)
  IF(ALLOCATED(YDTRC%GMU0_MAX))DEALLOCATE(YDTRC%GMU0_MAX)
END SUBROUTINE CLEAN_DATA
