PROGRAM MAIN
  USE YOMTRC, ONLY: TTRC
  USE MOD_CONSTANTS
  TYPE(TTRC) :: YDTRC
  INTEGER :: IBLK

  WRITE(*,*)"RUNNING"
  CALL INIT_CONSTANTS()

  CALL INIT_TTRC(YDTRC)

!$omp parallel do
  DO IBLK=1,NGPBLKS

    !To implement
    !CALL YDTRC%UPDATE_VIEW(IBLK)

    CALL COMPUTE(YDTRC)
  ENDDO
!$omp end parallel do

  CALL CLEAN_DATA(YDTRC)
END PROGRAM MAIN
