MODULE YOMTRC

USE MOD_CONSTANTS  ,ONLY : JPRB

IMPLICIT NONE

SAVE

TYPE :: TTRC
REAL(KIND=JPRB),ALLOCATABLE:: GRSURF  (:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GDEOTI  (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GDEOTI2 (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GUEOTI  (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GUEOTI2 (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GEOLT   (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GEOXT   (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GRPROX  (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GMIXP   (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GFLUXC  (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GDEOSI  (:,:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GUEOSI  (:,:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GMU0    (:,:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GMU0_MIN(:,:)
REAL(KIND=JPRB),ALLOCATABLE:: GMU0_MAX(:,:)

!You must implement those methods
!CONTAINS
  !PROCEDURE :: INIT => TTRC_TTRC 
  !PROCEDURE :: FINAL => TTRC_FINAL
  !PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW
END TYPE TTRC

END MODULE YOMTRC
