SUBROUTINE INIT_TTRC(YDTRC)
  USE YOMTRC, ONLY: TTRC
  USE MOD_CONSTANTS
  TYPE(TTRC), INTENT(INOUT) :: YDTRC

  ! storage for solar gaseous transmissions
  IF (NSORAYFR /= 1) THEN
    ALLOCATE(YDTRC%GDEOSI  (NPROMA,0:NFLEVG,  2,NGPBLKS))
    ALLOCATE(YDTRC%GUEOSI  (NPROMA,0:NFLEVG,  2,NGPBLKS))
    ALLOCATE(YDTRC%GMU0    (NPROMA,0:NSORAYFR-1,NGPBLKS))
    ALLOCATE(YDTRC%GMU0_MIN(NPROMA             ,NGPBLKS))
    ALLOCATE(YDTRC%GMU0_MAX(NPROMA             ,NGPBLKS))
      WRITE(*,*) 'GDEOSI   ',SIZE(YDTRC%GDEOSI  ),SHAPE(YDTRC%GDEOSI  )
      WRITE(*,*) 'GUEOSI   ',SIZE(YDTRC%GUEOSI  ),SHAPE(YDTRC%GUEOSI  )
      WRITE(*,*) 'GMU0     ',SIZE(YDTRC%GMU0    ),SHAPE(YDTRC%GMU0    )
      WRITE(*,*) 'GMU0_MIN ',SIZE(YDTRC%GMU0_MIN),SHAPE(YDTRC%GMU0_MIN)
      WRITE(*,*) 'GMU0_MAX ',SIZE(YDTRC%GMU0_MAX),SHAPE(YDTRC%GMU0_MAX)
  ENDIF

  ! storage for gaseous transmissions
  IF (NTHRAYFR /= 1) THEN
    ALLOCATE(YDTRC%GRSURF  (NPROMA,         NGPBLKS))
    ALLOCATE(YDTRC%GDEOTI  (NPROMA,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GDEOTI2 (NPROMA,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GUEOTI  (NPROMA,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GUEOTI2 (NPROMA,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GEOXT   (NPROMA,  NFLEVG,NGPBLKS))
      WRITE(*,*) 'GRSURF   ',SIZE(YDTRC%GRSURF ),SHAPE(YDTRC%GRSURF )
      WRITE(*,*) 'GDEOTI   ',SIZE(YDTRC%GDEOTI ),SHAPE(YDTRC%GDEOTI )
      WRITE(*,*) 'GDEOTI2  ',SIZE(YDTRC%GDEOTI2),SHAPE(YDTRC%GDEOTI2)
      WRITE(*,*) 'GUEOTI   ',SIZE(YDTRC%GUEOTI ),SHAPE(YDTRC%GUEOTI )
      WRITE(*,*) 'GUEOTI2  ',SIZE(YDTRC%GUEOTI2),SHAPE(YDTRC%GUEOTI2)
      WRITE(*,*) 'GEOXT    ',SIZE(YDTRC%GEOXT  ),SHAPE(YDTRC%GEOXT  )
    IF (LRPROX) THEN
      ALLOCATE(YDTRC%GEOLT (NPROMA,  NFLEVG,NGPBLKS))
      ALLOCATE(YDTRC%GRPROX(NPROMA,0:NFLEVG,NGPBLKS))
        WRITE(*,*) 'GEOLT    ',SIZE(YDTRC%GEOLT ),SHAPE(YDTRC%GEOLT )
        WRITE(*,*) 'GRPROX   ',SIZE(YDTRC%GRPROX),SHAPE(YDTRC%GRPROX)
    ENDIF
  ENDIF

  ! storage for bracketing weights and offset
  IF (NRAUTOEV/=1) THEN
    ALLOCATE(YDTRC%GMIXP (NPROMA,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GFLUXC(NPROMA,0:NFLEVG,NGPBLKS))
      WRITE(*,*) 'GMIXP    ',SIZE(YDTRC%GMIXP ),SHAPE(YDTRC%GMIXP )
      WRITE(*,*) 'GFLUXC   ',SIZE(YDTRC%GFLUXC),SHAPE(YDTRC%GFLUXC)
  ENDIF
END SUBROUTINE INIT_TTRC
