PROGRAM MAIN
  USE YOMTRC, ONLY: TTRC
  USE MOD_CONSTANTS
  TYPE(TTRC) :: YDTRC
  INTEGER :: I
  CALL INIT_CONSTANTS()

  CALL INIT_TTRC(YDTRC)

!$omp parallel do
  DO BLK=1,NGPBLKS

    !To implement
    !CALL YDTRC%UPDATE_VIEW(BLK)

    CALL COMPUTE(YDTRC)
  ENDDO
!$omp end parallel do

  CALL CLEAN_DATA(YDTRC)
END PROGRAM MAIN
