PROGRAM MAIN
  USE YOMTRC, ONLY: TTRC
  USE MOD_CONSTANTS
  TYPE(TTRC) :: YDTRC
  INTEGER :: I
  CALL INIT_CONSTANTS()
  CALL INIT_TTRC(YDTRC)
  DO I=1,10
    CALL COMPUTE(YDTRC)
  ENDDO
  CALL CLEAN_DATA(YDTRC)
END PROGRAM MAIN
