MODULE MOD_CONSTANTS
  IMPLICIT NONE

  INTEGER :: NPROMA = 32
  INTEGER :: NFLEVG = 50
  INTEGER :: NGPBLKS = 10

  INTEGER :: NSORAYFR = 0
  INTEGER :: NRAUTOEV = 0
  INTEGER :: NTHRAYFR = 0
  LOGICAL, PARAMETER :: LRPROX = .TRUE.
#ifdef PARKIND1_SINGLE
  INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(6,37)
#else
  INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13,300)
#endif

CONTAINS
  SUBROUTINE INIT_CONSTANTS()
    CALL SET_TO_0_OR_1(NSORAYFR)
    CALL SET_TO_0_OR_1(NRAUTOEV)
    CALL SET_TO_0_OR_1(NTHRAYFR)
  END SUBROUTINE INIT_CONSTANTS

  SUBROUTINE SET_TO_0_OR_1(V)
    IMPLICIT NONE
    INTEGER, INTENT(OUT) :: V
    REAL :: R

    CALL RANDOM_NUMBER(R)

    IF (R < 0.5) THEN
      V= 0
    ELSE
      V= 1
    END IF
  END SUBROUTINE SET_TO_0_OR_1
END MODULE MOD_CONSTANTS
